//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import "AWSCore/AWSCore.h"
//#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:1d9b865a-64d4-4d49-b4d4-3e151cab32ea"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"2ac6121cf1f84b359b2d6e78630e5719"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"pgt-tv-party"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub 17d24914-8c89-4e0a-aba6-ecea7f09c108 aws-my-sample-app-ios-objc-v0.6"
